#!/bin/bash


case $DISTRIB_TYPE in
	xfce)
		PACKAGE_LIST_DESKTOP+=" $PACKAGE_LIST_OFFICE"
		PACKAGE_LIST_DESKTOP+=" xfce4 lxtask xfce4-screenshooter xfce4-notifyd xfce4-terminal desktop-base software-properties-gtk thunar-archive-plugin xfce4-power-manager"
		PACKAGE_LIST_DESKTOP+=" update-manager"
	;;
	lxde)
		PACKAGE_LIST_DESKTOP+=" $PACKAGE_LIST_OFFICE"
		PACKAGE_LIST_DESKTOP+=" lxde lxlauncher lxmusic lxsession-default-apps lxsession-logout lxshortcut lxtask obconf \
			xfce4-power-manager-plugins lxde-common desktop-base"
	;;
	gnome)
		PACKAGE_LIST_DESKTOP+=" $PACKAGE_LIST_OFFICE"
		PACKAGE_LIST_DESKTOP+=" desktop-base software-properties-gtk gnome-terminal gnome-shell-extensions gnome-tweaks gnome-screenshot"
		([[ $DISTRIB_RELEASE == focal ]] || [[ $DISTRIB_RELEASE == jammy ]]) && PACKAGE_LIST_DESKTOP+=" yaru-theme-gtk yaru-theme-icon yaru-theme-sound"
		PACKAGE_LIST_DESKTOP+=" ubuntu-desktop update-manager"
	;;
esac

case $DISTRIB_RELEASE in
	bionic)
		DEBOOTSTRAP_COMPONENTS="main,universe"
		[[ "$DISTRIB_TYPE" != "minimal" ]] && PACKAGE_LIST_RELEASE="man-db kbd gnupg2 dirmngr networkd-dispatcher libjpeg9 libjpeg-turbo8-dev zlib1g-dev libpng-dev command-not-found hddtemp crda"
		PACKAGE_LIST_QT+=" libqt5multimediaquick-p5 libqgsttools-p1"
		PACKAGE_LIST_KODI="mesa-utils libglu1 libpcrecpp0v5 libssh-4 libtag1v5 libtinyxml2.6.2v5 libcurl4 libcrossguid0 libmariadbclient18 libmicrohttpd12 \
			libavahi-compat-libdnssd-dev libcec4 libfstrcmp0 libnfs11 fonts-liberation python-bluez python-pil python-simplejson libaacs0 fonts-dejavu-core libao-dev"
		PACKAGE_LIST_SERVER_KODI="libao4 libwayland-cursor0 libavahi-compat-libdnssd-dev libass9 libavahi-client3 libavahi-common3 libbluray2 libcdio17 libcec4 \
			libfreetype6 libfstrcmp0 libinput10 liblcms2-2 libmicrohttpd12 libnfs11 libpcrecpp0v5 libpulse0 libsmbclient libtag1v5 libtinyxml2.6.2v5 libxkbcommon0 \
			libxslt1.1 mesa-utils x11-utils fonts-liberation fonts-dejavu-core python-bluez python-pil python-simplejson libgif7 libvorbisfile3 libaacs0 libgnutls30 \
			libyajl2 libsndio6.1 libcrossguid0 libao-dev"
		PACKAGE_LIST_DESKTOP+=" $PACKAGE_LIST_XSERVER $PACKAGE_LIST_GSTREAMER $PACKAGE_LIST_QT $PACKAGE_LIST_KODI"
		PACKAGE_LIST_DESKTOP+=" chromium-browser xserver-xorg-input-all firefox pulseaudio-module-gconf libgnome2-perl language-selector-gnome"
	;;
	focal|hirsute)
		DEBOOTSTRAP_COMPONENTS="main,universe"
		[[ "$DISTRIB_TYPE" != "minimal" ]] && PACKAGE_LIST_RELEASE="man-db kbd gnupg2 dirmngr networkd-dispatcher libjpeg9 libjpeg-turbo8-dev zlib1g-dev libpng-dev command-not-found hddtemp crda"
		PACKAGE_LIST_KODI="mesa-utils libglu1 libpcrecpp0v5 libssh-4 libtag1v5 libtinyxml2.6.2v5 libcurl4 libcrossguid0  libmicrohttpd12 libavahi-compat-libdnssd-dev libcec4 \
			libfstrcmp0 libnfs13 fonts-liberation python-bluez python-pil python-simplejson libaacs0 fonts-dejavu-core libao-dev libpython2.7 libpython2.7-minimal libpython2.7-stdlib x11-utils"
		PACKAGE_LIST_SERVER_KODI="libao4 libwayland-cursor0 libavahi-compat-libdnssd-dev libass9 libavahi-client3 libavahi-common3 libbluray2 libcdio18 libcec4 \
			libfreetype6 libfstrcmp0 libinput10 liblcms2-2 libmicrohttpd12 libnfs13 libpcrecpp0v5 libpulse0 libsmbclient libtag1v5 libtinyxml2.6.2v5 libxkbcommon0 \
			libxslt1.1 mesa-utils x11-utils fonts-liberation fonts-dejavu-core python-bluez python-pil python-simplejson libgif7 libvorbisfile3 libaacs0 libgnutls30 \
			libyajl2 libsndio7.0 libcrossguid0 libao-dev libpython2.7"
		PACKAGE_LIST_MESA="libclang-cpp11 libclc-r600 libclc-amdgcn libllvm10"
		PACKAGE_LIST_DESKTOP+=" $PACKAGE_LIST_XSERVER $PACKAGE_LIST_GSTREAMER $PACKAGE_LIST_KODI $PACKAGE_LIST_MESA"
		PACKAGE_LIST_DESKTOP+=" xserver-xorg-input-all pulseaudio-module-gsettings firefox language-selector-gnome viewnior libreoffice-style-tango"
	;;
	jammy)
		DEBOOTSTRAP_COMPONENTS="main,universe"
		[[ "$DISTRIB_TYPE" != "minimal" ]] && PACKAGE_LIST_RELEASE="man-db kbd gnupg2 dirmngr networkd-dispatcher libjpeg9 libjpeg-turbo8-dev zlib1g-dev libpng-dev command-not-found"
		PACKAGE_LIST_DESKTOP+=" $PACKAGE_LIST_GSTREAMER xserver-xorg-input-all pulseaudio-module-gsettings firefox language-selector-gnome viewnior dbus-user-session libreoffice-style-tango"
		PACKAGE_LIST_DESKTOP+=" rhythmbox cheese gsettings-ubuntu-schemas "
	;;
esac

# add for debug tools
if [ "$BUILD_TYPE" == develop ]; then
	# add for GPU test
	PACKAGE_LIST_DESKTOP+=" glmark2-es2-wayland"
	
	# add common debug tool here for develop version
	PACKAGE_LIST+=" silversearcher-ag v4l-utils tilix adb "
fi


DEBIAN_MIRROR='ports.ubuntu.com/'

if [[ $DOWNLOAD_MIRROR == china ]] ; then
	DEBIAN_MIRROR='mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/'
fi

# apt-cacher-ng mirror configuration
APT_MIRROR=$DEBIAN_MIRROR



