#!/bin/bash

PACKAGE_LIST_DESKTOP+=" pavucontrol pavumeter blueman libpam-gnome-keyring gnome-online-accounts gkbd-capplet gnome-calculator gnome-calendar \
			gnome-characters gnome-disk-utility gnome-font-viewer gnome-logs gnome-mahjongg gnome-sudoku gnome-system-monitor \
			gnome-todo gnome-user-docs gnome-video-effects gnome-power-manager libgnome-autoar-0-0 libgnome-autoar-0-0 \
			gnome-todo-common gnome-todo gnome-orca libgnome-bluetooth13 pulseaudio-module-bluetooth pulseaudio \
			network-manager-gnome network-manager-openvpn-gnome gnome-keyring gnome-system-tools libcanberra-pulse"

case $DISTRIB_TYPE in
	xfce)
		PACKAGE_LIST_DESKTOP+=" $PACKAGE_LIST_OFFICE"
		PACKAGE_LIST_DESKTOP+=" xfce4 lxtask xfce4-screenshooter xfce4-notifyd xfce4-terminal desktop-base software-properties-gtk thunar-archive-plugin xfce4-power-manager"
	;;
	lxde)
		PACKAGE_LIST_DESKTOP+=" $PACKAGE_LIST_OFFICE"
		PACKAGE_LIST_DESKTOP+=" lxde lxlauncher lxmusic lxsession-default-apps lxsession-logout lxshortcut lxtask obconf \
			xfce4-power-manager-plugins lxde-common desktop-base"
	;;
	gnome)
		PACKAGE_LIST_DESKTOP+=" $PACKAGE_LIST_OFFICE"
		PACKAGE_LIST_DESKTOP+=" desktop-base software-properties-gtk gnome-terminal gnome-tweaks gnome-screenshot gnome-bluetooth"
		([[ $DISTRIB_RELEASE == focal ]] || [[ $DISTRIB_RELEASE == jammy ]]) && PACKAGE_LIST_DESKTOP+=" yaru-theme-gtk yaru-theme-icon yaru-theme-sound"
		PACKAGE_LIST_DESKTOP+=" ubuntu-desktop libgdk-pixbuf2.0-bin "
	;;
esac

case $DISTRIB_RELEASE in
	jammy)
		DEBOOTSTRAP_COMPONENTS="main,universe"
		[[ "$DISTRIB_TYPE" != "minimal" ]] && PACKAGE_LIST_RELEASE="man-db kbd gnupg2 dirmngr networkd-dispatcher libjpeg9 libjpeg-turbo8-dev zlib1g-dev libpng-dev command-not-found"
		PACKAGE_LIST_DESKTOP+=" $PACKAGE_LIST_GSTREAMER $PACKAGE_LIST_QT xserver-xorg-input-all pulseaudio-module-gsettings language-selector-gnome viewnior dbus-user-session libreoffice-style-tango"
		PACKAGE_LIST_DESKTOP+=" rhythmbox cheese network-manager-config-connectivity-ubuntu gsettings-ubuntu-schemas chromium-browser "
	;;
esac

# add for debug tools
if [ "$BUILD_TYPE" == develop ]; then
	# add for GPU test
	PACKAGE_LIST_DESKTOP+=" glmark2-es2-wayland"
	
	# add common debug tool here for develop version
	PACKAGE_LIST+=" silversearcher-ag v4l-utils tilix adb python3-pip "
fi


DEBIAN_MIRROR='ports.ubuntu.com/'

if [[ $DOWNLOAD_MIRROR == china ]] ; then
	DEBIAN_MIRROR='mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/'
fi

# apt-cacher-ng mirror configuration
APT_MIRROR=$DEBIAN_MIRROR

# add chromium-browser ppa source
add_chromium_ppa_source() {
	info_msg "add chromium-browser ppa source"
	eval 'LC_ALL=C LANG=C chroot $ROOTFS_TEMP /bin/bash -c "echo | add-apt-repository ppa:saiarcot895/chromium-beta"'
}

## Install  check-language-support
Install_check_language_support() {
	## For chinese language and input method
	if [[ $SUPPORT_LANGUAGE == CHS ]] ; then
		#shell_chroot "apt-get install language-pack-zh-hans -y"
		#shell_chroot "apt install $(check-language-support) -y"
		info_msg "Installing check-language-support"
		if [ $DISTRIB_RELEASE != "bullseye" ] && [ $DISTRIB_RELEASE != "bookworm" ];then
			info_msg "Installing chromium-browser-l10n"
			eval 'LC_ALL=C LANG=C chroot $ROOTFS_TEMP /bin/bash -c "apt-get install chromium-browser-l10n=1:107.0.5304.62-0ubuntu1~ppa1~22.04.1 -y"'
		fi
		shell_chroot "apt install _AML_PRE_BRACKET_check-language-support_AML_POST_BRACKET_ -y"
	fi
}

