#!/bin/bash

# amlbian build configs


DISTRIBUTION_ARRAY=("Ubuntu" "Debian")
DISTRIBUTION_ARRAY_DESC=("Ubuntu" "Debian")
Ubuntu_RELEASE_ARRAY=("bionic" "focal" "jammy")
Ubuntu_RELEASE_VERSION_ARRAY=("18.04" "20.04" "22.04")
Ubuntu_RELEASE_ARRAY_DESC=("Ubuntu 18.04" "Ubuntu 20.04" "Ubuntu 22.04")
Debian_RELEASE_ARRAY=("buster" "bullseye")
Debian_RELEASE_VERSION_ARRAY=("10" "11")
Debian_RELEASE_ARRAY_DESC=("Debian 10" "Debian 11")
DISTRIB_ARCH_ARRAY=("arm64")
Ubuntu_TYPE_ARRAY=("server" "minimal" "xfce" "lxde" "gnome")
Ubuntu_TYPE_ARRAY_DESC=("Headless Image With Essential Packages"\
						"Minimal Image With Very Basic Packages"\
						"Desktop Image With XFCE Desktop"\
						"Desktop Image With LXDE Desktop"\
						"Desktop Image With GNOME Desktop")
Debian_TYPE_ARRAY=("server" "minimal" "xfce" "lxde" "gnome")
Debian_TYPE_ARRAY_DESC=("Headless Image With Essential Packages"\
						"Minimal Image With Very Basic Packages"\
						"Desktop Image With XFCE Desktop"\
						"Desktop Image With LXDE Desktop"\
						"Desktop Image With GNOME Desktop")
INSTALL_TYPE_ARRAY=("EMMC" "SD-USB")
INSTALL_TYPE_ARRAY_DESC=("Image For Writing to eMMC Storage With USB Burning Tool"\
						 "Image For Writing to SD/USB Storage")

DISTRIBUTION_ARRAY_LEN=${#DISTRIBUTION_ARRAY[@]}
Ubuntu_RELEASE_ARRAY_LEN=${#Ubuntu_RELEASE_ARRAY[@]}
Debian_RELEASE_ARRAY_LEN=${#Debian_RELEASE_ARRAY[@]}
DISTRIB_ARCH_ARRAY_LEN=${#DISTRIB_ARCH_ARRAY[@]}
Ubuntu_TYPE_ARRAY_LEN=${#Ubuntu_TYPE_ARRAY[@]}
Debian_TYPE_ARRAY_LEN=${#Debian_TYPE_ARRAY[@]}
INSTALL_TYPE_ARRAY_LEN=${#INSTALL_TYPE_ARRAY[@]}


